import type { Metadata } from "next";
import { EB_Garamond, Poppins } from "next/font/google";
import { MainLayout } from '@/components/layout/main-layout';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { themes } from '@/lib/themes';
import "./globals.css";

const garamond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-garamond",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const themes = ${JSON.stringify(themes)};
                  const theme = localStorage.getItem('theme');
                  if (theme && themes[theme]) {
                    // Remove all theme classes
                    document.documentElement.classList.remove(...Object.keys(themes));
                    document.documentElement.classList.add(theme);
                    
                    // Apply theme variables
                    const themeConfig = themes[theme];
                    const style = document.documentElement.style;
                    Object.entries(themeConfig).forEach(([key, value]) => {
                      if (typeof value === 'string' && !key.includes('gradient')) {
                        style.setProperty('--' + key, value);
                      }
                    });
                  }
                } catch {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${garamond.variable} ${poppins.variable} font-sans antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
